// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/configuration_service.go
//
// Generated by this command:
//
//	mockgen --source=internal/service/configuration_service.go --destination=internal/service/mock/mock_configuration_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigurationService is a mock of ConfigurationService interface.
type MockConfigurationService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationServiceMockRecorder
	isgomock struct{}
}

// MockConfigurationServiceMockRecorder is the mock recorder for MockConfigurationService.
type MockConfigurationServiceMockRecorder struct {
	mock *MockConfigurationService
}

// NewMockConfigurationService creates a new mock instance.
func NewMockConfigurationService(ctrl *gomock.Controller) *MockConfigurationService {
	mock := &MockConfigurationService{ctrl: ctrl}
	mock.recorder = &MockConfigurationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurationService) EXPECT() *MockConfigurationServiceMockRecorder {
	return m.recorder
}

// RunDatabaseMigration mocks base method.
func (m *MockConfigurationService) RunDatabaseMigration(config *model.MigrationConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunDatabaseMigration", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunDatabaseMigration indicates an expected call of RunDatabaseMigration.
func (mr *MockConfigurationServiceMockRecorder) RunDatabaseMigration(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunDatabaseMigration", reflect.TypeOf((*MockConfigurationService)(nil).RunDatabaseMigration), config)
}
