// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/damage_type_service.go
//
// Generated by this command:
//
//	mockgen --source=internal/service/damage_type_service.go --destination=internal/service/mock/mock_damage_type_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDamageTypeService is a mock of DamageTypeService interface.
type MockDamageTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockDamageTypeServiceMockRecorder
	isgomock struct{}
}

// MockDamageTypeServiceMockRecorder is the mock recorder for MockDamageTypeService.
type MockDamageTypeServiceMockRecorder struct {
	mock *MockDamageTypeService
}

// NewMockDamageTypeService creates a new mock instance.
func NewMockDamageTypeService(ctrl *gomock.Controller) *MockDamageTypeService {
	mock := &MockDamageTypeService{ctrl: ctrl}
	mock.recorder = &MockDamageTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDamageTypeService) EXPECT() *MockDamageTypeServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDamageTypeService) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDamageTypeServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDamageTypeService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockDamageTypeService) GetAll() (*[]model.DamageType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]model.DamageType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDamageTypeServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDamageTypeService)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockDamageTypeService) GetByID(id string) (*model.DamageType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.DamageType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDamageTypeServiceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDamageTypeService)(nil).GetByID), id)
}

// Save mocks base method.
func (m *MockDamageTypeService) Save(damageType model.DamageType) (*model.DamageType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", damageType)
	ret0, _ := ret[0].(*model.DamageType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockDamageTypeServiceMockRecorder) Save(damageType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDamageTypeService)(nil).Save), damageType)
}
