// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/creature_service.go
//
// Generated by this command:
//
//	mockgen --source=internal/service/creature_service.go --destination=internal/service/mock/mock_creature_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCreatureService is a mock of CreatureService interface.
type MockCreatureService struct {
	ctrl     *gomock.Controller
	recorder *MockCreatureServiceMockRecorder
	isgomock struct{}
}

// MockCreatureServiceMockRecorder is the mock recorder for MockCreatureService.
type MockCreatureServiceMockRecorder struct {
	mock *MockCreatureService
}

// NewMockCreatureService creates a new mock instance.
func NewMockCreatureService(ctrl *gomock.Controller) *MockCreatureService {
	mock := &MockCreatureService{ctrl: ctrl}
	mock.recorder = &MockCreatureServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatureService) EXPECT() *MockCreatureServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCreatureService) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCreatureServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCreatureService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockCreatureService) GetAll() (*[]model.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]model.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCreatureServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCreatureService)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockCreatureService) GetByID(id string) (*model.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCreatureServiceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCreatureService)(nil).GetByID), id)
}

// Save mocks base method.
func (m *MockCreatureService) Save(creature model.Creature) (*model.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", creature)
	ret0, _ := ret[0].(*model.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockCreatureServiceMockRecorder) Save(creature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCreatureService)(nil).Save), creature)
}
