// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/ability_service.go
//
// Generated by this command:
//
//	mockgen --source=internal/service/ability_service.go --destination=internal/service/mock/mock_ability_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAbilityService is a mock of AbilityService interface.
type MockAbilityService struct {
	ctrl     *gomock.Controller
	recorder *MockAbilityServiceMockRecorder
	isgomock struct{}
}

// MockAbilityServiceMockRecorder is the mock recorder for MockAbilityService.
type MockAbilityServiceMockRecorder struct {
	mock *MockAbilityService
}

// NewMockAbilityService creates a new mock instance.
func NewMockAbilityService(ctrl *gomock.Controller) *MockAbilityService {
	mock := &MockAbilityService{ctrl: ctrl}
	mock.recorder = &MockAbilityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbilityService) EXPECT() *MockAbilityServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAbilityService) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAbilityServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAbilityService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockAbilityService) GetAll() (*[]model.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]model.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAbilityServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAbilityService)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockAbilityService) GetByID(id string) (*model.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAbilityServiceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAbilityService)(nil).GetByID), id)
}

// Save mocks base method.
func (m *MockAbilityService) Save(ability model.Ability) (*model.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ability)
	ret0, _ := ret[0].(*model.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockAbilityServiceMockRecorder) Save(ability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAbilityService)(nil).Save), ability)
}
