// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/health_service.go
//
// Generated by this command:
//
//	mockgen --source=internal/service/health_service.go --destination=internal/service/mock/mock_health_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHealthService is a mock of HealthService interface.
type MockHealthService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServiceMockRecorder
	isgomock struct{}
}

// MockHealthServiceMockRecorder is the mock recorder for MockHealthService.
type MockHealthServiceMockRecorder struct {
	mock *MockHealthService
}

// NewMockHealthService creates a new mock instance.
func NewMockHealthService(ctrl *gomock.Controller) *MockHealthService {
	mock := &MockHealthService{ctrl: ctrl}
	mock.recorder = &MockHealthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthService) EXPECT() *MockHealthServiceMockRecorder {
	return m.recorder
}

// GetDatabaseVersion mocks base method.
func (m *MockHealthService) GetDatabaseVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabaseVersion indicates an expected call of GetDatabaseVersion.
func (mr *MockHealthServiceMockRecorder) GetDatabaseVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseVersion", reflect.TypeOf((*MockHealthService)(nil).GetDatabaseVersion))
}
