// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/creature_repository.go
//
// Generated by this command:
//
//	mockgen --source=internal/repository/creature_repository.go --destination=internal/repository/mock/mock_creature_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCreatureRepository is a mock of CreatureRepository interface.
type MockCreatureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreatureRepositoryMockRecorder
	isgomock struct{}
}

// MockCreatureRepositoryMockRecorder is the mock recorder for MockCreatureRepository.
type MockCreatureRepositoryMockRecorder struct {
	mock *MockCreatureRepository
}

// NewMockCreatureRepository creates a new mock instance.
func NewMockCreatureRepository(ctrl *gomock.Controller) *MockCreatureRepository {
	mock := &MockCreatureRepository{ctrl: ctrl}
	mock.recorder = &MockCreatureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatureRepository) EXPECT() *MockCreatureRepositoryMockRecorder {
	return m.recorder
}

// DeleteSlotsByCreatureID mocks base method.
func (m *MockCreatureRepository) DeleteSlotsByCreatureID(creatureID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSlotsByCreatureID", creatureID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSlotsByCreatureID indicates an expected call of DeleteSlotsByCreatureID.
func (mr *MockCreatureRepositoryMockRecorder) DeleteSlotsByCreatureID(creatureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSlotsByCreatureID", reflect.TypeOf((*MockCreatureRepository)(nil).DeleteSlotsByCreatureID), creatureID)
}

// GetAll mocks base method.
func (m *MockCreatureRepository) GetAll() (*[]model.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]model.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCreatureRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCreatureRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockCreatureRepository) GetByID(id string) (*model.Creature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Creature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCreatureRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCreatureRepository)(nil).GetByID), id)
}

// GetSlotsByCreatureID mocks base method.
func (m *MockCreatureRepository) GetSlotsByCreatureID(creatureID string) (*[]model.AbilitySlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlotsByCreatureID", creatureID)
	ret0, _ := ret[0].(*[]model.AbilitySlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotsByCreatureID indicates an expected call of GetSlotsByCreatureID.
func (mr *MockCreatureRepositoryMockRecorder) GetSlotsByCreatureID(creatureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlotsByCreatureID", reflect.TypeOf((*MockCreatureRepository)(nil).GetSlotsByCreatureID), creatureID)
}

// Upsert mocks base method.
func (m *MockCreatureRepository) Upsert(c model.Creature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCreatureRepositoryMockRecorder) Upsert(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCreatureRepository)(nil).Upsert), c)
}

// UpsertSlot mocks base method.
func (m *MockCreatureRepository) UpsertSlot(slot model.AbilitySlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSlot", slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSlot indicates an expected call of UpsertSlot.
func (mr *MockCreatureRepositoryMockRecorder) UpsertSlot(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSlot", reflect.TypeOf((*MockCreatureRepository)(nil).UpsertSlot), slot)
}
