// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/damage_type_repository.go
//
// Generated by this command:
//
//	mockgen --source=internal/repository/damage_type_repository.go --destination=internal/repository/mock/mock_damage_type_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDamageTypeRepository is a mock of DamageTypeRepository interface.
type MockDamageTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDamageTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockDamageTypeRepositoryMockRecorder is the mock recorder for MockDamageTypeRepository.
type MockDamageTypeRepositoryMockRecorder struct {
	mock *MockDamageTypeRepository
}

// NewMockDamageTypeRepository creates a new mock instance.
func NewMockDamageTypeRepository(ctrl *gomock.Controller) *MockDamageTypeRepository {
	mock := &MockDamageTypeRepository{ctrl: ctrl}
	mock.recorder = &MockDamageTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDamageTypeRepository) EXPECT() *MockDamageTypeRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockDamageTypeRepository) GetAll() (*[]model.DamageType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]model.DamageType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDamageTypeRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDamageTypeRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockDamageTypeRepository) GetByID(id string) (*model.DamageType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.DamageType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDamageTypeRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDamageTypeRepository)(nil).GetByID), id)
}

// Upsert mocks base method.
func (m *MockDamageTypeRepository) Upsert(d model.DamageType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDamageTypeRepositoryMockRecorder) Upsert(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDamageTypeRepository)(nil).Upsert), d)
}
