// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/ability_repository.go
//
// Generated by this command:
//
//	mockgen --source=internal/repository/ability_repository.go --destination=internal/repository/mock/mock_ability_repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAbilityRepository is a mock of AbilityRepository interface.
type MockAbilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAbilityRepositoryMockRecorder
	isgomock struct{}
}

// MockAbilityRepositoryMockRecorder is the mock recorder for MockAbilityRepository.
type MockAbilityRepositoryMockRecorder struct {
	mock *MockAbilityRepository
}

// NewMockAbilityRepository creates a new mock instance.
func NewMockAbilityRepository(ctrl *gomock.Controller) *MockAbilityRepository {
	mock := &MockAbilityRepository{ctrl: ctrl}
	mock.recorder = &MockAbilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbilityRepository) EXPECT() *MockAbilityRepositoryMockRecorder {
	return m.recorder
}

// DeleteEffectsByAbilityID mocks base method.
func (m *MockAbilityRepository) DeleteEffectsByAbilityID(abilityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEffectsByAbilityID", abilityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEffectsByAbilityID indicates an expected call of DeleteEffectsByAbilityID.
func (mr *MockAbilityRepositoryMockRecorder) DeleteEffectsByAbilityID(abilityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEffectsByAbilityID", reflect.TypeOf((*MockAbilityRepository)(nil).DeleteEffectsByAbilityID), abilityID)
}

// GetAll mocks base method.
func (m *MockAbilityRepository) GetAll() (*[]model.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]model.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAbilityRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAbilityRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockAbilityRepository) GetByID(id string) (*model.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAbilityRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAbilityRepository)(nil).GetByID), id)
}

// GetEffectsByAbilityID mocks base method.
func (m *MockAbilityRepository) GetEffectsByAbilityID(abilityID string) (*[]model.AbilityEffect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectsByAbilityID", abilityID)
	ret0, _ := ret[0].(*[]model.AbilityEffect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEffectsByAbilityID indicates an expected call of GetEffectsByAbilityID.
func (mr *MockAbilityRepositoryMockRecorder) GetEffectsByAbilityID(abilityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectsByAbilityID", reflect.TypeOf((*MockAbilityRepository)(nil).GetEffectsByAbilityID), abilityID)
}

// Upsert mocks base method.
func (m *MockAbilityRepository) Upsert(a model.Ability) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAbilityRepositoryMockRecorder) Upsert(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAbilityRepository)(nil).Upsert), a)
}

// UpsertEffect mocks base method.
func (m *MockAbilityRepository) UpsertEffect(e model.AbilityEffect) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEffect", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEffect indicates an expected call of UpsertEffect.
func (mr *MockAbilityRepositoryMockRecorder) UpsertEffect(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEffect", reflect.TypeOf((*MockAbilityRepository)(nil).UpsertEffect), e)
}
