// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/database.go
//
// Generated by this command:
//
//	mockgen --source=internal/database/database.go --destination=internal/database/mock/mock_database.go
//

// Package mock_database is a generated GoMock package.
package mock_database

import (
	sql "database/sql"
	reflect "reflect"

	model "github.com/ccthomas/board-game/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockDatabase) Connect() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockDatabaseMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDatabase)(nil).Connect))
}

// GetConnection mocks base method.
func (m *MockDatabase) GetConnection() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockDatabaseMockRecorder) GetConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockDatabase)(nil).GetConnection))
}

// MigrationDown mocks base method.
func (m *MockDatabase) MigrationDown() (*model.MigrationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationDown")
	ret0, _ := ret[0].(*model.MigrationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrationDown indicates an expected call of MigrationDown.
func (mr *MockDatabaseMockRecorder) MigrationDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationDown", reflect.TypeOf((*MockDatabase)(nil).MigrationDown))
}

// MigrationStatus mocks base method.
func (m *MockDatabase) MigrationStatus() (*model.MigrationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationStatus")
	ret0, _ := ret[0].(*model.MigrationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrationStatus indicates an expected call of MigrationStatus.
func (mr *MockDatabaseMockRecorder) MigrationStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationStatus", reflect.TypeOf((*MockDatabase)(nil).MigrationStatus))
}

// MigrationSteps mocks base method.
func (m *MockDatabase) MigrationSteps(steps int8) (*model.MigrationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationSteps", steps)
	ret0, _ := ret[0].(*model.MigrationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrationSteps indicates an expected call of MigrationSteps.
func (mr *MockDatabaseMockRecorder) MigrationSteps(steps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationSteps", reflect.TypeOf((*MockDatabase)(nil).MigrationSteps), steps)
}

// MigrationUp mocks base method.
func (m *MockDatabase) MigrationUp() (*model.MigrationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationUp")
	ret0, _ := ret[0].(*model.MigrationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrationUp indicates an expected call of MigrationUp.
func (mr *MockDatabaseMockRecorder) MigrationUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationUp", reflect.TypeOf((*MockDatabase)(nil).MigrationUp))
}

// Version mocks base method.
func (m *MockDatabase) Version() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockDatabaseMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockDatabase)(nil).Version))
}
