// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/database.go
//
// Generated by this command:
//
//	mockgen --source=internal/database/database.go --destination=internal/database/mock/mock_database.go
//

// Package mock_database is a generated GoMock package.
package mock_database

import (
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockDatabase) Connect() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockDatabaseMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDatabase)(nil).Connect))
}

// GetConnection mocks base method.
func (m *MockDatabase) GetConnection() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockDatabaseMockRecorder) GetConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockDatabase)(nil).GetConnection))
}

// MigrationDown mocks base method.
func (m *MockDatabase) MigrationDown(db *sql.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationDown", db)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrationDown indicates an expected call of MigrationDown.
func (mr *MockDatabaseMockRecorder) MigrationDown(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationDown", reflect.TypeOf((*MockDatabase)(nil).MigrationDown), db)
}

// MigrationSteps mocks base method.
func (m *MockDatabase) MigrationSteps(db *sql.DB, steps int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationSteps", db, steps)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrationSteps indicates an expected call of MigrationSteps.
func (mr *MockDatabaseMockRecorder) MigrationSteps(db, steps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationSteps", reflect.TypeOf((*MockDatabase)(nil).MigrationSteps), db, steps)
}

// MigrationUp mocks base method.
func (m *MockDatabase) MigrationUp(db *sql.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrationUp", db)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrationUp indicates an expected call of MigrationUp.
func (mr *MockDatabaseMockRecorder) MigrationUp(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrationUp", reflect.TypeOf((*MockDatabase)(nil).MigrationUp), db)
}

// Version mocks base method.
func (m *MockDatabase) Version() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockDatabaseMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockDatabase)(nil).Version))
}
